### ISSUE TITLE
Stable: credentials for .ovpn not Remembered post reboot

### ISSUE THREAD

**Issue by wellloaded** [Windscribe/Desktop-App#105]
As I'm using an external .ovpn I'm asked to provide the credentials when connecting. I provide them and it works just fine.
I also select "Remember" in the bottom left of the popup however this latter setting doesn't appear to be working. If I reboot the device I find it stuck (not connected) asking for credentials again.

**Comment by bernerdad** [comment]
Hi and thank you for bring this issue to our attention.  We've added it to our dev board for investigation asap.

**Comment by bernerdad** [comment]
Hi.  We're unable to reproduce this issue here.  Credentials for our custom ovpn configs are being saved and automatically applied when we reboot.  The only way we can replicate this is if we don't allow the Windscribe app to shut down normally (i.e. we task kill it).  To further troubleshoot this, we'll require the app log and a sanitized copy of your custom ovpn config.  Is there any chance the custom ovpn config file name is changing?  We map the file name to the credentials, so a file name change would mean any previously stored credentials would be ignored.

**Comment by wellloaded** [comment]
The .ovpn is stored locally on the device so I exclude the .ovpn changes its name or content.
Since the device is accessed remotely (rdp) I can't really comment if any app is killed rather than closed. Is there any way I can better verify this?

That said I have updated to the latest guinea_pig, rebooted and this finally (after about 1 month of this behavior) seems to be fixed. You might have fixed indirectly touching some other part of the code (e.g. DNS resolution towards router?) not sure.

Still I have rebooted twice and the credentials are now remembered. Go figure.

Thanks for the support you can close this.

**Comment by wellloaded** [comment]
Is there any update on this please? I'm asked for credentials every time i reboot the device. So the "Rememebr credentials" is not working as expected not even on v2.22.10

**Comment by jaxu** [comment]
Sorry, the re-opening of this seems to have slipped off our radar.  I've opened a ticket on our board and this should be resolved in the next release (2.24.x).

Most likely this is due to the credentials not being flushed to disk until app shutdown, and if you restart your computer and the app doesn't get a clean shutdown it may never write it.  I'll change this to immediately write to disk, but in the meantime you can work around this by quitting the app and restarting it after saving your credentials, and that should cause them to save permanently.
